const UNIFIED_PRESET_CONFIG = Object.freeze({
    STRATEGY_PRESET: 'unified',
    SIMULATION_MODE: 'unified-live',
    BACKTEST_INITIAL_EQUITY: 50,
    USE_CLOSED_CANDLE_SIGNALS: true,
    UNIFIED_MODE: true,
    RISK_PERCENTAGE: 5,
    DAILY_TRADE_LIMIT: 1,
    MAX_DAILY_LOSSES: 1,
    BOT_START_HOUR: 8,
    BOT_END_HOUR: 23,
    MIN_CONFLUENCE_SCORE: 6,
    MIN_SCORE_EDGE: 3,
    REJECT_TIE_SCORE: false,
    REQUIRE_DIRECTIONAL_TRIGGER: false,
    MIN_EMA_SEPARATION: 0,
    MAX_SIGNAL_RANGE_ATR: 3.5,
    ADX_THRESHOLD: 33,
    ATR_STOP_MULTIPLIER: 0.2,
    PARTIAL_TP_RR: 100,
    FINAL_TP_RR: 2,
    MIN_REWARD_TO_RISK: 1.5,
    MAX_DOLLAR_RISK: 0,
    BREAKEVEN_TRIGGER_RR: 1.5,
    TRAILING_START_RR: 0.6,
    TRAILING_STOP_ATR_MULTIPLIER: 1,
    MAX_ATR_PERCENT_OF_PRICE: 0.04,
    MAX_SL_PERCENT_OF_PRICE: 0.04,
    CONFLUENCE_LOT_SCALING: true,
    CONFLUENCE_LOT_START_SCORE: 7,
    CONFLUENCE_MAX_RISK_PERCENTAGE: 7.5,
    TRADING_MIN_BTC_QTY: 0.01,
    TRADING_MAX_BTC_QTY: 0.06,
    TRADING_LOT_STEP_BTC: 0.01,
    ALLOW_LONG_TRADES: true,
    ALLOW_SHORT_TRADES: true
});

function getUnifiedPresetConfig(overrides = {}) {
    return { ...UNIFIED_PRESET_CONFIG, ...overrides };
}

module.exports = {
    UNIFIED_PRESET_CONFIG,
    getUnifiedPresetConfig
};
